from langchain.vectorstores import VectorStore
from langchain_core.language_models.chat_models import BaseChatModel
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver

from chatbot.agents import RouterAgent, SQLAgent, VizAgent
from chatbot.contexts import BaseContextProvider
from chatbot.formatters import BasePromptFormatter

from .formatting import format_router_agent_response
from .messages import SQLVizAssistantMessage


class AsyncSQLVizAssistant:
    """Async LLM-powered assistant for querying and visualizing databases.

    Args:
        model (BaseChatModel):
            A langchain `BaseChatModel` instance with tool-calling support.
        context_provider (BaseContextProvider):
            A context provider that supplies all metadata needed by the agent. Implement
            this abstract base to plug in any data source (BigQuery, Postgres, etc.)
            without changing the agent's orchestration logic.
        prompt_formatter (BasePromptFormatter):
            A formatter responsible for constructing the LLM system prompt during SQL generation step,
            based on the user's question and optional few-shot examples. Must implement how examples
            are retrieved and how the prompt template is composed.
        checkpointer (AsyncPostgresSaver | None, optional):
            A checkpointer that will be used for persisting per-thread state across
            assistant's runs. If set to `None`, the assistant will not retain memory
            of previous messages. Defaults to `None`.
        viz_vector_store (VectorStore | None, optional):
            A vector database containing examples for the `VizAgent` LLM calls.
            If set to `None`, no examples will be used. Defaults to `None`.
        question_limit (int | None, optional):
            Maximum number of Q&A turns to retain in the conversation history
            sent to the model. If set to `None`, the context is unlimited. Defaults to `None`.

    Raises:
        TypeError: If the provided checkpointer or vector stores are of the wrong type.
    """

    def __init__(
        self,
        model: BaseChatModel,
        context_provider: BaseContextProvider,
        prompt_formatter: BasePromptFormatter,
        checkpointer: AsyncPostgresSaver | None = None,
        viz_vector_store: VectorStore | None = None,
        question_limit: int | None = 5,
    ):
        if checkpointer is None:
            subgraph_checkpointer = None
        elif isinstance(checkpointer, AsyncPostgresSaver):
            subgraph_checkpointer = True
        else:
            raise TypeError(
                "`checkpointer` must be an instance of langgraph `PostgresSaver` "
                f"or `None`, but got `{type(checkpointer)}`."
            )

        sql_agent = SQLAgent(
            model=model,
            context_provider=context_provider,
            prompt_formatter=prompt_formatter,
            checkpointer=subgraph_checkpointer,
            question_limit=question_limit
        )

        viz_agent = VizAgent(
            model=model,
            checkpointer=subgraph_checkpointer,
            vector_store=viz_vector_store,
            question_limit=question_limit
        )

        self.router_agent = RouterAgent(
            model=model,
            sql_agent=sql_agent,
            viz_agent=viz_agent,
            checkpointer=checkpointer,
            question_limit=question_limit
        )

    async def invoke(self, message: str, config: dict|None=None) -> SQLVizAssistantMessage:
        """Asynchronously sends a message to the `RouterAgent` and returns its response.

        Args:
            message (str): The input message.
            config (dict | None, optional): Optional configuration for the agent execution.
                Refer to https://python.langchain.com/docs/concepts/runnables/#runnableconfig
                for a list of allowed properties.

        Returns:
            SQLVizAssistantMessage: The structured response generated by the assistant.
        """
        response = await self.router_agent.ainvoke(message, config)
        response = format_router_agent_response(response)

        if config is not None and "run_id" in config:
            response["id"] = config["run_id"]

        return SQLVizAssistantMessage(**response)

    async def clear_thread(self, thread_id: str):
        """Asynchronously deletes all checkpoints for a given thread.

        Args:
            thread_id (str): The thread unique identifier.
        """
        await self.router_agent.aclear_thread(thread_id)
