from langchain.vectorstores import VectorStore
from langchain_core.language_models.chat_models import BaseChatModel
from langgraph.checkpoint.postgres import PostgresSaver

from chatbot.agents import RouterAgent, SQLAgent, VizAgent
from chatbot.databases import Database

from .formatting import format_router_agent_response
from .messages import SQLVizAssistantMessage


class SQLVizAssistant:
    """LLM-powered assistant for querying and visualizing databases.

    Args:
        database (Database):
            A `Database` object implementing the `Database` protocol.
        model (BaseChatModel):
            A langchain `ChatModel` with support to structured outputs and tool calling.
        checkpointer (PostgresSaver | None, optional):
            A checkpointer that will be used for persisting state across assistant's runs.
            If set to `None`, the assistant will not retain memory of previous messages.
            Defaults to `None`.
        sql_vector_store (VectorStore | None, optional):
            A vector store that contains examples for the `SQLAgent` LLM calls.
            If set to `None`, no examples will be used. Defaults to `None`.
        viz_vector_store (VectorStore | None, optional):
            A vector store that contains examples for the `VizAgent` LLM calls.
            If set to `None`, no examples will be used. Defaults to `None`.
        question_limit (int | None, optional):
            Maximum number of previous questions to keep in memory.
            If `None`, all questions are kept. Defaults to `5`.

    Raises:
        TypeError: If the provided checkpointer or vector stores are of the wrong type.
    """

    def __init__(
        self,
        database: Database,
        model: BaseChatModel,
        checkpointer: PostgresSaver | None = None,
        sql_vector_store: VectorStore | None = None,
        viz_vector_store: VectorStore | None = None,
        question_limit: int | None = 5,
    ):
        if checkpointer is None:
            subgraph_checkpointer = None
        elif isinstance(checkpointer, PostgresSaver):
            subgraph_checkpointer = True
        else:
            raise TypeError(
                "`checkpointer` must be an instance of langgraph `PostgresSaver` "
                f"or `None`, but got `{type(checkpointer)}`."
            )

        if sql_vector_store is not None and not isinstance(sql_vector_store, VectorStore) \
        or viz_vector_store is not None and not isinstance(viz_vector_store, VectorStore):
            raise TypeError(
                "`sql_vector_store` and `viz_vector_store` must be instances of langchain `VectorStore` or `None`, "
                f"but got `sql_vector_store`: {type(sql_vector_store)}, `viz_vector_store`: {type(viz_vector_store)}."
            )

        sql_agent = SQLAgent(
            db=database,
            model=model,
            checkpointer=subgraph_checkpointer,
            vector_store=sql_vector_store,
            question_limit=question_limit
        )

        viz_agent = VizAgent(
            model=model,
            checkpointer=subgraph_checkpointer,
            vector_store=viz_vector_store,
            question_limit=question_limit
        )

        self.router_agent = RouterAgent(
            model=model,
            sql_agent=sql_agent,
            viz_agent=viz_agent,
            checkpointer=checkpointer,
            question_limit=question_limit
        )

    def invoke(self, message: str, config: dict|None=None) -> SQLVizAssistantMessage:
        """Sends a message to the `RouterAgent` and returns its response.

        Args:
            message (str): The input message.
            config (dict | None, optional): Optional configuration for the agent execution.
                Refer to https://python.langchain.com/docs/concepts/runnables/#runnableconfig
                for a list of allowed properties.

        Returns:
            SQLVizAssistantMessage: The structured response generated by the assistant.
        """
        response = self.router_agent.invoke(message, config)
        response = format_router_agent_response(response)

        if config is not None and "run_id" in config:
            response["id"] = config["run_id"]

        return SQLVizAssistantMessage(**response)

    def clear_thread(self, thread_id: str):
        """Deletes all checkpoints for a given thread.

        Args:
            thread_id (str): The thread unique identifier.
        """
        self.router_agent.clear_thread(thread_id)
