name: CI Chatbot

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install pipx
          pipx install poetry==1.8.3

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          cd chatbot
          poetry install

      - name: Set up directory permissions
        run: |
          sudo mkdir -p /var/log/chatbot
          sudo chown -R $USER:$USER /var/log/chatbot

      - name: Run tests
        run: |
          . .venv/bin/activate
          cd chatbot
          pytest
